name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-server-startup:
    environment: env
    runs-on: ubuntu-latest
    env:
      PORT: 8000
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ZILLIZ_AUTH_TOKEN: ${{ secrets.ZILLIZ_AUTH_TOKEN }}
      ZILLIZ_URL: ${{ secrets.ZILLIZ_URL }}
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      AZURE_AI_SEARCH_ENDPOINT: ${{ secrets.AZURE_AI_SEARCH_ENDPOINT }}
      AZURE_AI_SEARCH_API_KEY: ${{ secrets.AZURE_AI_SEARCH_API_KEY }}
      AZURE_MONGO_CONNECTION_STRING: $ {{ secrets.AZURE_MONGO_CONNECTION_STRING }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start server in the background
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port $PORT &
          sleep 15

      - name: Check server health
        run: curl -f http://127.0.0.1:$PORT || exit 1

      - name: Kill server
        run: pkill uvicorn
